[2025-08-03T23:00:05.388+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-03T23:00:05.409+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T16:00:04.028134+00:00 [queued]>
[2025-08-03T23:00:05.418+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T16:00:04.028134+00:00 [queued]>
[2025-08-03T23:00:05.419+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-03T23:00:05.432+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-08-03 16:00:04.028134+00:00
[2025-08-03T23:00:05.436+0700] {standard_task_runner.py:63} INFO - Started process 211 to run task
[2025-08-03T23:00:05.439+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stress_level_detection_pipeline', 'preprocess_data', 'manual__2025-08-03T16:00:04.028134+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stress_detection_dag.py', '--cfg-path', '/tmp/tmpwin90ucr']
[2025-08-03T23:00:05.442+0700] {standard_task_runner.py:91} INFO - Job 3: Subtask preprocess_data
[2025-08-03T23:00:05.517+0700] {task_command.py:426} INFO - Running <TaskInstance: stress_level_detection_pipeline.preprocess_data manual__2025-08-03T16:00:04.028134+00:00 [running]> on host 024a2ea8b349
[2025-08-03T23:00:05.594+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stress_level_detection_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T16:00:04.028134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T16:00:04.028134+00:00'
[2025-08-03T23:00:05.596+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-03T23:00:05.619+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-03T23:00:05.619+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stress_detection_dag.py", line 12, in preprocess_data
    df = pd.read_excel(input_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-08-03T23:00:05.638+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stress_level_detection_pipeline, task_id=preprocess_data, run_id=manual__2025-08-03T16:00:04.028134+00:00, execution_date=20250803T160004, start_date=20250803T160005, end_date=20250803T160005
[2025-08-03T23:00:05.650+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task preprocess_data (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 211)
[2025-08-03T23:00:05.693+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-03T23:00:05.709+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-03T23:00:05.715+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
